spring:
  application:
    name: capacityservice
  profiles:
    active:
      default
    cloud:
      config:
        enabled: true
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
#    platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://capacity.cty1gon9nn61.us-east-2.rds.amazonaws.com:3306/capacity?user=admin&password=admin123123
    initialization-mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
        
server:
  port: 7100
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
